# Generated by Django 4.0.3 on 2023-03-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
